version: "3"

services:
  query-node:
    image: hydra-test:latest
    restart: unless-stopped
    environment:
      - DB_NAME=processor-db
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - GRAPHQL_SERVER_HOST=localhost
      - GRAPHQL_SERVER_PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - hydra-processor
    command: ["yarn", "query-node:start:prod"]

  hydra-processor:
    image: hydra-test:latest
    restart: unless-stopped
    environment:
      - DB_NAME=processor-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - TYPEORM_DATABASE=processor-db
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=postgres
      - GRAPHQL_SERVER_HOST=localhost
      - GRAPHQL_SERVER_PORT=4000
      - TYPEORM_HOST=db
      - TYPEORM_PORT=5432
      - INDEXER_ENDPOINT_URL=http://hydra-indexer-gateway:8080/v1/graphql
      - NODE_URL=ws://node-template:9944
      - POLL_INTERVAL_MS=500 # refresh every second
      - DEBUG=hydra-processor:*
    ports:
      - "3000:3000"
    depends_on:
      - hydra-indexer-gateway
    command: >
      sh -c "yarn query-node:configure && \
             yarn bootstrap && \
             yarn typegen && \
             yarn mappings:build && \
             yarn processor:start"

  hydra-indexer:
    image: hydra-indexer:latest
    restart: unless-stopped
    environment:
      - DB_NAME=indexer-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - NEW_BLOCK_TIMEOUT_SEC=150000
      - WS_PROVIDER_ENDPOINT_URI=ws://node-template:9944/
      - REDIS_URI=redis://redis:6379/0
      - DEBUG=index-builder:*
      - TYPES_JSON=typedefs.json
    volumes:
      - ./fixtures/typedefs.json:/home/hydra/packages/hydra-indexer/typedefs.json
    command: >
      sh -c "yarn db:bootstrap && yarn start:prod"
    depends_on:
      - node-template
      - redis
      - db

  hydra-indexer-gateway:
    image: hydra-indexer-gateway:latest
    restart: unless-stopped
    depends_on:
      - redis
      - db
      - hydra-indexer-status-service
      - hydra-indexer
    ports:
      - "8080:8080"
    environment:
      # DEV_MODE: "true"
      HYDRA_INDEXER_DB: postgres://postgres:postgres@db:5432/indexer-db
      HYDRA_INDEXER_STATUS_SERVICE: http://hydra-indexer-status-service:8081/status

  hydra-indexer-status-service:
    image: hydra-indexer-status-service:latest
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "8081:8081"
    environment:
      REDIS_URI: redis://redis:6379/0
      PORT: 8081

  node-template:
    image: paritytech/substrate-playground-template-node-template:sha-7212614
    restart: unless-stopped
    ports:
      - "9944:9944"
    command: ["./target/release/node-template", "--dev", "--tmp", "--ws-external"]

  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379"

  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
