name: bump
on:
  push:
    branches:
      - master
      - dev
      - ci-test
      - ci-lerna
      - ci-lerna-test
      - hydra-v3
  workflow_dispatch:

env:
  CI: true

jobs:
  bump:
    name: Bump version
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Authenticate with Registry
        run: |
          echo "Branch name: ${{ steps.extract_branch.outputs.branch }}"
          yarn logout
          echo "always-auth=true" > .npmrc
          echo "@subsquid:registry=https://registry.npmjs.org/" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Install  
        run: |
          yarn install --frozen-lockfile
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: Lerna update prerelease version
        if: steps.extract_branch.outputs.branch != 'master'
        run: |
          yarn lerna version --conventional-commits --conventional-prerelease --preid ${{ steps.extract_branch.outputs.branch }} --yes
      - name: Lerna update prerelease version master
        if: steps.extract_branch.outputs.branch == 'master'
        run: |
          yarn lerna version --conventional-commits --conventional-prerelease --yes
