name: hydra-e2e-tests
on: [pull_request]

jobs:
  run_e2e_tests:
    name: run Hydra e2e tests
    if: "!contains(github.event.head_commit.message, 'test skip')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      #  continue-on-error: true
      - name: run e2e tests
        run: ./scripts/e2e-test.sh
