name: hydra-unit-tests
on: [pull_request]
  
jobs:
  run_unit_tests:
    name: run Hydra unit tests
    if: "!contains(github.event.head_commit.message, 'test skip')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
#      - name: lint
#        run:
      - name: run unit tests
        run: |
          npm ci
          npx tsc
          ./scripts/test.sh
