name: hydra-e2e-tests
on: [pull_request, workflow_dispatch]

jobs:
  run_e2e_tests:
    name: run Hydra e2e tests
    if: "!contains(github.event.head_commit.message, 'test skip')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: run e2e tests
        run: ./scripts/e2e-test.sh
